### ISSUE TITLE
Unable to import private modules with `DENO_AUTH_TOKENS`

### ISSUE THREAD

**Issue by linhub15** [denoland/deploy_feedback#261]
Reproduction steps

1. Given a file that imports from a private repository `import { ... } from "https://raw.githubusercontent.com/<private-repo>"`
2. Deploy
3. See the error 
![image](https://user-images.githubusercontent.com/10420994/183341388-26a0a2ca-f082-441c-8bba-fa51a5959d51.png)
4. Add environment variable `DENO_AUTH_TOKENS` with github access token format `<token>@raw.githubusercontent.com;`
![image](https://user-images.githubusercontent.com/10420994/183341259-5476b2e2-81fb-43d1-bb45-85e36d58d396.png)
5. Expect Deploy to automatically add the `Authorization: Bearer <token>` and succeed in importing the module.
6. Actual: Still see the `404 Not Found`

Setting local environment variable `DENO_AUTH_TOKENS`  in `~/.bashrc` working successfully.

**Comment by schwarzkopfb** [comment]
I just faced the exact same issue but I tried `deployctl` for uploading.

**Comment by Anderson-SG** [comment]
Same error here, Trying to deploy using Github Actions, I have DENO_AUTH_TOKENS correctly registered both on the deploy mat and on the Deno Deploy panel and I keep getting an error because he can't access the repository at the time of deploy.

Error: 
![image](https://user-images.githubusercontent.com/37317374/235336838-83efbb3a-685a-4243-8ca6-0b9c1ec8d65a.png)

Secreted Created on Github:
![image](https://user-images.githubusercontent.com/37317374/235336737-3ce1da45-4b68-4264-bb5f-b5c1c5a49e0a.png)

Secret Created on DenoDeploy
![image](https://user-images.githubusercontent.com/37317374/235336761-bb421187-21d6-48a2-a88b-b8b903fab7eb.png)

The content of the registered variable is the following:
```
MY_PAT_TOKEN_HERE@raw.githubusercontent.com
```

I already tested it, and locally on my machine I can use a variable with that same content normally.

Github Action: 
```yaml
name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        
       # Just a workarround try, no success.
      - name: Export DENO_AUTH_TOKENS secret to env
        run: echo "export DENO_AUTH_TOKENS=${{ secrets.DENO_AUTH_TOKENS }}" >> ~/.bashrc && source ~/.bashrc

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "xxx-project-name"
          entrypoint: "./server.ts"
```
