### ISSUE TITLE
Relative import path Error (GitHub actions deployment)

### ISSUE THREAD

**Issue by moncefplastin07** [denoland/deploy_feedback#277]
Hey guys, I hope you are happy
I'm having trouble trying to publish my last project with Deno Fresh to Deno Deploy with GitHub Actions

the Error is:
``Error: The deployment failed: Relative import path "$fresh/server.ts" not prefixed with / or ./ or ../``
![image](https://user-images.githubusercontent.com/26319214/187154049-ef3cfa6c-d4a1-4026-9362-16020594faca.png)

But when I automate the project publishing process ithe ``Automatic`` option without GitHub actions, it will be published normally

It seems that the problem in import_map.json handling in GitHub action Deployments

**Comment by doronaviguy** [comment]
I have added 
`                  import-map: "import_map.json"`
to `.github/workflows/deno.yml` 

And the issue is solved

```
            - name: Upload to Deno Deploy
              uses: denoland/deployctl@v1
              with:
                  project: "ton"
                  import-map: "import_map.json"
                 ```
