### ISSUE TITLE
Can't deploy a Nuxt app to deno.. TypeError terminated

### ISSUE THREAD

**Issue by engrpeters** [denoland/deploy_feedback#308]
I'm trying to deploy to deno this is what my workflow file looks like 

```
    name: Deploy
    
    on: [push]
    
    jobs:
    
    deploy:
    
    name: Deploy
    
    runs-on: ubuntu-latest
    
    permissions:
    
    id-token: write  # Needed for auth with Deno Deploy
    
    contents: read  # Needed to clone the repository
    
      
    
    steps:
    
    - name: Clone repository
    
    uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
    
    with:
    
    node-version: 14.18.0
    
      
    
    # TODO: add a build step here
    
    - run: "yarn install"
    
    - run: "yarn build"
    
    - name: Upload to Deno Deploy
    
    uses: denoland/deployctl@v1
    
    with:
    
    project: "engrpeters-tbnhd"
    
    entrypoint: " .output/server/index.mjs"  # TODO: update entrypoint


```

Could someone tell me please . What I'm doing wrong here
