### ISSUE TITLE
[Bug]: Cannot find private modules, lack of `DENO_AUTH_TOKENS`

### ISSUE THREAD

**Issue by dogukanakkaya** [denoland/deploy_feedback#484]
### Problem description

I am trying to deploy my Fresh app and i have a custom GitHub action for it, see:
```yml
name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DENO_AUTH_TOKENS: ${{ secrets.DENO_AUTH_TOKENS }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.36.x

      - name: Build step
        run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: my-project-name
          entrypoint: main.ts
          root: .
```

Problem is as you can see I have the `DENO_AUTH_TOKENS` secret set. Build is working correctly (it wasn't before having that env) but the deploy step does not work.  I assume Deno Deploy does not export that env in the machine that it downloads the dependency when downloading modules:
> Error: The deployment failed: HTTP status client error (404 Not Found) for url (https://raw.githubusercontent.com/dogukanakkaya/...)

I also tried to set that variable in Deno Deploy dashboard, project settings page. But it does not allow you to set any env variable name that starts with `DENO_` so I could not do that either.

### Steps to reproduce

Just try to deploy a Deno application that imports a private module.

### Expected behavior

It should either get and set the same environment variables from GitHub actions or should allow to have it set manually from dashboard.

### Environment

- Deno version: v1.36.4
