### ISSUE TITLE
[Bug]:  Deployment of a sveltke-kit app fails, telling me that I'm not using the svelte-deno-adapter when I am.

### ISSUE THREAD

**Issue by pdenapo** [denoland/deploy_feedback#485]
### Problem description

I have a svelte-kit app in Deno Deploy.

When I imported in into deno, it complais that it is not using svelte-adapter-deno. But this is not true.

Here is my svelte.config.js

```js
import adapter from 'svelte-adapter-deno';


/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		// adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
		// If your environment is not supported or you settled on a specific environment, switch out the adapter.
		// See https://kit.svelte.dev/docs/adapters for more information about adapters.
		adapter: adapter()
	}
};

export default config;
```

and it is also in package.json.

When commiting to github after that, the deploy fails with a strange message in the deploy log

Finishing deployment...
Error: TypeError: terminated

However, my site just works in Deno Deploy.

### Steps to reproduce

clone my repository  

https://github.com/pdenapo/svelte-app-deno.git 

and import in into Deno Deploy

### Expected behavior

Deploy the site without errors.

### Environment

Everthing is done through github actions

```yml
name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm and node_modules
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Copy bootstrap 
        run:  ./copiar_en_static.sh
        shell: bash     

      - name: Build site
        run: pnpm build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: far-deer-44
          entrypoint: 'build/index.js' 
```
