### ISSUE TITLE
[KV Feedback]: "Queues not available on preview environment" error in production environment

### ISSUE THREAD

**Issue by yorinasub17** [denoland/deploy_feedback#516]
### 🔍

- [X] Did you search for existing issues?

### Type of feedback

Bug report

### Description

I have gotten into a state where a deployed app is promoted to production, but I get an error message that Queues is not available on a preview environment.

### Steps to reproduce (if applicable)

I don't have concrete steps for reproducing this since I haven't had the time to explore various scenarios. However, I have a sneaking suspicion that there is some kind of race condition between the swapping of environments to the new version, and existing requests.

The reason I think that is because this only started happening once I introduced a release testing workflow, where an automated test script waits for the deployment to finish and as soon as it detects Deno Deploy finishes it's routine, it starts hitting it with requests to perform a smoke test. Some of those initial requests pass (which suggest it is hitting the old environment), before they start to fail after a few seconds (which suggest they are hitting the new environment).

I did not see this happen at all when I was testing manually after releasing, which is why it makes me think that this has something to do with a live request being handled by the old environment at the boundary.

### Expected behavior (if applicable)

Queues should be available on production environments.

### Additional context

Logs from live prod environment:

<img width="998" alt="Screenshot_2023-10-02_at_4_06_26 PM" src="https://github.com/denoland/deploy_feedback/assets/430092/6d5e8b8b-bb0c-414b-abd1-f2e643894299">

**Comment by yorinasub17** [comment]
It appears that this might be the same issue as https://github.com/denoland/deploy_feedback/issues/517, in that the KV is just not available for the first X minutes of the service. I'm observing that the problem magically goes away after waiting 5-8 minutes after a deploy.

**Comment by igorzi** [comment]
@yorinasub17 fix for #517 rolled out earlier today. are you still seeing this issue?

**Comment by yorinasub17** [comment]
Apologies for the delay. Yes that appears to have addressed this issue! I haven't run into this today across multiple deployments. Closing as solved!

**Comment by yorinasub17** [comment]
@igorzi Reopening as it looks like this issue is back. This was ok for a while, but I have run into this a few times today now. I am again observing that if the service is hit soon after deployment, queues are not available because it isn't considered production.

<img width="692" alt="fensak-stage_-_Project_-_Deploy" src="https://github.com/denoland/deploy_feedback/assets/430092/e94694ee-bc63-4da1-96ae-54222874bead">

**Comment by igorzi** [comment]
@yorinasub17 do you only see this with deployments, which were first preview and then promoted to production?

Have you seen this issue on deployments, which were created as production deployments? (e.g. from main branch)

**Comment by yorinasub17** [comment]
I'm actually using the GitHub Actions based deployment, and only to deploy from the `main` branch, which my understanding is that it is a straight production deployment (no preview environments).

As a side note, it almost always resolves when I do a re-run on the GitHub Actions job to trigger a redeployment (in fact, this is the primary reason I'm doing it this way so I can trigger redeployments with ease).

Here's a snippet of the workflow file:

```
  deployprod:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to auth to Deno Deploy
      checks: write # Needed for GHA to write the checks for the job
      contents: read
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0

      - uses: denoland/deployctl@b841621a76eae438b09e1bce5e74549678c24e7f # v1.8.2
        with:
          project: fensak
          entrypoint: main.ts
```
