### ISSUE TITLE
How to use DENO_AUTH_TOKENS for deploy

### ISSUE THREAD

**Issue by faramos** [denoland/deploy_feedback#531]
Hi,

I'm trying to integrate a new project that references some modules in a private GitHub repository. I'm using DENO_AUTH_TOKENS and import maps, and everything functions as expected in my local dev environment. However:

In "No build step" mode, as far as I know, I'm not allowed to set up these tokens.
When switching to a GitHub Actions workflow, I configured this environment variable at the root, but it fails at the "Upload to Deno Deploy" step with a "module not found" error.
Currently, my workflow file looks like this:

```yaml
name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  DENO_AUTH_TOKENS: ${{ secrets.DENO_AUTH_TOKENS }}
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "my-project-name"
          entrypoint: "main.ts" # 📝 Update the entrypoint if necessary
          root: "." # 📝 Update the root if necessary

```

Any assistance would be greatly appreciated, and thank you for your incredible contributions!
