### ISSUE TITLE
[Bug]: Failed to resolve module "mysql2"

### ISSUE THREAD

**Issue by yjavaherian** [denoland/deploy_feedback#760]
### Problem description

Hi. im trying to deploy my first fresh project with deno deploy. all goes well until the final step of "Upload to DenoDeploy" in my github action which i get the following error:

Error: The deployment failed: BOOT_FAILURE

Failed to resolve module "mysql2" from "file:///node_modules/.deno/drizzle-orm@0.36.4/node_modules/drizzle-orm/mysql2/driver.js"

off course i have this module in my deno.json file and i even install it using npm in the install section just to be sure.
i have no problem running my code locally and so I do not understand where the problem is.

### Steps to reproduce

try to deploy using the following github action:

```
name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "npm install mysql2"

      - name: Build step
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DOWNLOAD_URL: ${{ secrets.DOWNLOAD_URL }}
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "libgen"
          entrypoint: "main.ts"
          root: "."
 ```

### Expected behavior

to be able to successfully deploy my webapp

### Environment

- Deno version: 2.1.1
